FORMAT: 1A
HOST: http://104.130.226.110:5000/

# nobelprize

nobelprize is an api to get various information about nobel prizes, their laureates, and the countries they are from

#group Prizes

## Prize collection [/api/prize]

### List All Prizes [GET]

+ Response 200 (application/json)

        {
          "num_results": 573,
          "objects": [
            {
              "category": "physics",
              "id": 1,
              "laureates": [
                {
                  "country_id": "JP",
                  "date_of_birth": "0000-00-00",
                  "gender": "male",
                  "id": 1,
                  "name": "Takaaki Kajita",
                  "nr_prizes": 1,
                  "url": "/laureates/Takaaki_Kajita"
                }, ...
              ]
            }, ...
          ]
        }
        
## Prize by id [/api/prize/{id}]

### Get Prizes By ID [GET]

+ Parameters
    + id (required, number, `1`) ... Int `id` of the Nobel Prize associated with id
    
+ Response 200 (application/json)

        {
          "category": "physics",
          "id": 1,
          "laureates": [
            {
              "country_id": "JP",
              "date_of_birth": "0000-00-00",
              "gender": "male",
              "id": 1,
              "name": "Takaaki Kajita",
              "nr_prizes": 1,
              "url": "/laureates/Takaaki_Kajita"
            },
            {
              "country_id": "CA",
              "date_of_birth": "0000-00-00",
              "gender": "male",
              "id": 2,
              "name": "Arthur B. McDonald",
              "nr_prizes": 1,
              "url": "/laureates/Arthur_B._McDonald"
            }
          ],
          "nr_laureates": 2,
          "year": 2015
        }
        
## Prize by filter [/api/prize?q={filter}]

### List Prizes By filter [GET]

+ Parameters
    + filter (required, json, `{"filters":[{"name":"year","op":"==","val":2015}]}`) ... A json filter. "year" can be replaced by any other attribute of prize. "==" can be replaced with other operations like "<" or "!=". 2015 can be replaced by another year in interest. 
    
+ Response 200 (application/json)

        
        {
          "num_results": 6,
          "objects": [
            {
              "category": "physics",
              "id": 1,
              "laureates": [
                {
                  "country_id": "JP",
                  "date_of_birth": "0000-00-00",
                  "gender": "male",
                  "id": 1,
                  "name": "Takaaki Kajita",
                  "nr_prizes": 1,
                  "url": "/laureates/Takaaki_Kajita"
                }, ...
              ]
            }, ...
          ]
        }

#group Laureates

## Laureate collection [/api/laureate]

### List All Laureates [GET]

+ Response 200 (application/json)

        {
          "num_results": 895,
          "objects": [
            {
              "country_id": "JP",
              "date_of_birth": "0000-00-00",
              "gender": "male",
              "id": 1,
              "name": "Takaaki Kajita",
              "nr_prizes": 1
            }, ...
          ]
        }
        
## Laureate by id [/api/laureate/{id}]

### Get Laureate By ID [GET]

+ Parameters
    + id (required, number, `1`) ... Int `id` of the laureate associated with id
   
+ Response 200 (application/json)

        {
          "country_id": "JP",
          "date_of_birth": "0000-00-00",
          "gender": "male",
          "id": 1,
          "name": "Takaaki Kajita",
          "nr_prizes": 1
        }
        
## Laureate by filter [/api/laureate?q={filter}]
        
### List Laureates By filter [GET]

+ Parameters
    + filter (required, json, `{"filters":[{"name":"name","op":"==","val":"Arthur B. McDonald"}]}`) ... A json filter. "name" can be replaced by any other attribute of laureate. "==" can be replaced with other operations like "<" or "!=". "Arthur B. McDonald" can be replaced by another name in interest.

+ Response 200 (application/json)

        {
          "num_results": 1,
          "objects": [
            {
              "country_id": "CA",
              "date_of_birth": "0000-00-00",
              "gender": "male",
              "id": 2,
              "name": "Arthur B. McDonald",
              "nr_prizes": 1
            }
          ],
          "page": 1,
          "total_pages": 1
        }
        
#group Countries

## Country collection [/api/country]

### List All Countries [GET]

+ Response 200 (application/json)

        {
          "num_results": 76,
          "objects": [
            {
              "country_code": "AR",
              "laureates": [
                {
                  "country_id": "AR",
                  "date_of_birth": "1927-10-08",
                  "gender": "male",
                  "id": 354,
                  "name": "César Milstein",
                  "nr_prizes": 1,
                  "url": "/laureates/César_Milstein"
                }, ...
              ]
            }, ...
          ]
        }


## Country by code [/api/country/{country_code}]
        
### Get Country By Country Code [GET]

+ Parameters
    + country_code (required, number, `CA`) ... String `country_code` of a country in interest
    
+ Response 200 (application/json)

        
        {
          "country_code": "CA",
          "laureates": [
            {
              "country_id": "CA",
              "date_of_birth": "0000-00-00",
              "gender": "male",
              "id": 2,
              "name": "Arthur B. McDonald",
              "nr_prizes": 1,
              "url": "/laureates/Arthur_B._McDonald"
            }, ...
           ]
        }
        
## Country by filter [/api/country?q={filter}]
        
### List Country By filter [GET]

+ Parameters
    + filter (required, json, `{"filters":[{"name":"name","op":"==","val":"bulgaria"}]}`) ... A json filter. "name" can be replaced by any other attribute of country. "==" can be replaced with other operations like "<" or "!=". "bulgaria" can be replaced by another name in interest.

+ Response 200 (application/json)

        {
          "num_results": 1,
          "objects": [
            {
              "country_code": "BG",
              "laureates": [
                {
                  "country_id": "BG",
                  "date_of_birth": "1905-07-25",
                  "gender": "male",
                  "id": 382,
                  "name": "Elias Canetti",
                  "nr_prizes": 1,
                  "url": "/laureates/Elias_Canetti"
                }
              ],
              "name": "Bulgaria",
              "nr_laureates": 1,
              "nr_prizes": 1,
              "population": 7202198
            }
          ],
          "page": 1,
          "total_pages": 1
        }